services:
  # Backend API service
  - type: web
    name: smart-quiz-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    autoDeploy: false
    envVars:

      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "False" 

  # Frontend static site
  - type: web
    name: smart-quiz-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    autoDeploy: false
    envVars:
      - key: API_BASE_URL
        value: http://smart-quiz-backend.onrender.com/api