apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: my-postgres-db
  namespace: smart-quiz-app
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando_user:
      - superuser
      - createdb
  databases:
    my_database: zalando_user
  postgresql:
    version: "15"
