apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: smart-quiz-app
type: Opaque
data:
  POSTGRES_USER: c3JldGVuZ2xhdmluY2Vza2k=
  POSTGRES_PASSWORD: UGFzc3dvcmQxMjMhQA==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: smart-quiz-app
data:
  POSTGRES_DB: postgres_db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: smart-quiz-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quiz-db-deployment
  namespace: smart-quiz-app
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: quiz-db
  template:
    metadata:
      labels:
        app: quiz-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: smart-quiz-app
spec:
  clusterIP: None
  selector:
    app: quiz-db
  ports:
    - port: 5432
      name: postgres