apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env-url
  namespace: smart-quiz-app
data:
  API_BASE_URL: "http://smartquiz.home/backend/api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: smart-quiz-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-ctr
          image: sretenglavinceski/devops-project-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-env-url
                  key: API_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: smart-quiz-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 80
  type: ClusterIP
          

