name: Build & Push Docker images, and Deploy changes to Kubernetes cluster 

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Django Tests
        working-directory: ./backend
        run: python manage.py test


  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            sretenglavinceski/devops-project-backend:latest
            sretenglavinceski/devops-project-backend:${{ env.IMAGE_TAG }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            sretenglavinceski/devops-project-frontend:latest
            sretenglavinceski/devops-project-frontend:${{ env.IMAGE_TAG }}
    
  deploy-local:
    needs: build-and-push
    runs-on: self-hosted
    env:
      KUBECONFIG: C:\Users\glavi\.kube\config
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Kubernetes Context
        run: kubectl config use-context k3d-cicd-project
        shell: powershell

      - name: Update Backend Deployment in k8s
        run: kubectl set image deployment/backend-deploy backend-ctr=sretenglavinceski/devops-project-backend:${{ env.IMAGE_TAG }} -n smart-quiz-app
        shell: powershell

      - name: Update Frontend Deployment in k8s
        run: kubectl set image deployment/frontend-deploy frontend-ctr=sretenglavinceski/devops-project-frontend:${{ env.IMAGE_TAG }} -n smart-quiz-app
        shell: powershell
  
  deploy-cloud:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Trigger Backend Deploy on Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}

      - name: Trigger Frontend Deploy on Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
